nama: Build APK
pada: [tekan]
Pekerjaan:
  membangun:
    berjalan pada: ubuntu-22.04
    tangga:
      - penggunaan: actions/checkout@v4
      - penggunaan: actions/setup-node@v4
        dengan:
          versi node: '20'
      - menggunakan: actions/setup-java@v4
        dengan:
          distribusi: 'temurin'
          versi java: '17'
      - jalankan: npm install -g cordova
      - jalankan: cordova platform add android@13.0.0
      - nama: Membangun Cordova Android
        lingkungan:
          URL_DISTRIBUSI_GRADLE_ANDROID_CORDOVA: 'https://services.gradle.org/distributions/gradle-8.7-all.zip'
        jalankan: cordova build android
      - penggunaan: actions/upload-artifact@v4
        dengan:
          nama: Fake-Quotes-APK
          jalur: platforms/android/app/build/outputs/apk/debug/app-debug.apk
